from pydantic import Field, field_validator
from typing import Dict, Union, Optional

from .baseRequestWithProxy import BaseRequestWithProxy


class GeetestRequest(BaseRequestWithProxy):
    """
    Represents a payload structure for solving GeeTest challenges.

    Attributes:
        type: The constant string value identifying the task type as "GeeTestTask".
        websiteUrl: The URL of the webpage containing the GeeTest challenge.
        gt: The public GeeTest key retrieved from the target website, identifying
            the GeeTest account/challenge configuration.
        challenge: A one-time token generated by the target website for each
            challenge attempt. Required when solving GeeTest version 3.
        version: The GeeTest challenge version to solve, either 3 or 4.
        initParameters: Additional initialization parameters used by GeeTest
            version 4 challenges, if the website requires them.
        geetestApiServerSubdomain: The custom API server subdomain used by the
            target website's GeeTest widget, if it deviates from the default.
        geetestGetLib: Path to the captcha script used to display it on the
            page, sent as a JSON string. Optional; may be required for some sites.
        user_agent: Browser User-Agent to emulate. Pass only a current
            Windows OS UA.
    """
    type: str = Field(default='GeeTestTask', description='The constant string value identifying the task type as "GeeTestTask".')
    websiteUrl: str = Field(..., description='The URL of the webpage containing the GeeTest challenge.')
    gt: str = Field(..., description='The public GeeTest key retrieved from the target website, identifying the GeeTest account/challenge configuration.')
    challenge: Optional[str] = Field(default=None, description='A one-time token generated by the target website for each challenge attempt. Required when solving GeeTest version 3.')
    version: int = Field(default=3, description='The GeeTest challenge version to solve, either 3 or 4.')
    initParameters: Optional[Dict] = Field(default=None, description="Additional initialization parameters used by GeeTest version 4 challenges, if the website requires them.")
    geetestApiServerSubdomain: Optional[str] = Field(default=None, description="The custom API server subdomain used by the target website's GeeTest widget, if it deviates from the default.")
    geetestGetLib: Optional[str] = Field(default=None, description='Path to the captcha script used to display it on the page, sent as a JSON string. Optional; may be required for some sites.')
    user_agent: Optional[str] = Field(default=None, description='Browser User-Agent to emulate. Pass only a current Windows OS UA.')

    @field_validator('version')
    @classmethod
    def validate_version(cls, value):
        if value not in [3, 4]:
            raise ValueError(f"Geetest version could be 3 or 4, not {value}")
        return value
    
    def getTaskDict(self) -> Dict[str, Union[str, int, bool]]:
        task = {}
        task['type'] = self.type
        task['websiteURL'] = self.websiteUrl
        task['gt'] = self.gt
        task['version'] = self.version
        
        if self.version == 3:
            if self.challenge is None:
                raise ValueError(f'Challenge value is required for 3 version Geetest.')
            task['challenge'] = self.challenge
        
        if self.version == 4:
            if self.initParameters is not None:
                task['initParameters'] = self.initParameters
                
        if self.geetestApiServerSubdomain is not None:
            task['geetestApiServerSubdomain'] = self.geetestApiServerSubdomain
        if self.geetestGetLib is not None:
            task['geetestGetLib'] = self.geetestGetLib
        if self.user_agent is not None:
            task['userAgent'] = self.user_agent
        
        if self.proxy:
            task['proxyType'] = self.proxy.proxyType
            task['proxyAddress'] = self.proxy.proxyAddress
            task['proxyPort'] = self.proxy.proxyPort
            task['proxyLogin'] = self.proxy.proxyLogin
            task['proxyPassword'] = self.proxy.proxyPassword
        return task